Fix errors in katoolin.py (Manjaro & Ubuntu)
File "/bin/katoolin", line 8
    print "Sorry. This script requires sudo privledges"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Sorry. This script requires sudo privledges")?